# -*- coding: utf-8 -*-
"""Projeto-transformacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bRrgJU-pq89IOk-tpEfEC3CcsPVXyJVa
"""

hospedagem = 'https://cdn3.gnarususercontent.com.br/2928-transformacao-manipulacao-dados/dados_hospedagem.json'
imoveis_disponiveis = 'https://cdn3.gnarususercontent.com.br/2928-transformacao-manipulacao-dados/moveis_disponiveis.json'

import pandas as pd

pd.read_json(hospedagem)

df_hospedagem = pd.read_json(hospedagem)

df_normalizado_hospedagem = pd.json_normalize(df_hospedagem['info_moveis'])

df_normalizado_hospedagem.head()

colunas = list(df_normalizado_hospedagem.columns)
colunas

df_normalizado_hospedagem.explode(colunas[3:])

df_normalizado_hospedagem = df_normalizado_hospedagem.explode(colunas[3:])

df_normalizado_hospedagem.reset_index(inplace=True,drop=True)

df_normalizado_hospedagem.head()

df_normalizado_hospedagem.info()

import numpy as np

df_normalizado_hospedagem['max_hospedes'] = df_normalizado_hospedagem['max_hospedes'].astype(np.int64)

df_normalizado_hospedagem.info()

col_numericas = ['quantidade_banheiros', 'quantidade_quartos', 'quantidade_camas']

df_normalizado_hospedagem[col_numericas] = df_normalizado_hospedagem[col_numericas].astype(np.int64)

df_normalizado_hospedagem.info()

df_normalizado_hospedagem['avaliacao_geral'].astype(np.float64)

df_normalizado_hospedagem['avaliacao_geral'] = df_normalizado_hospedagem['avaliacao_geral'].astype(np.float64)

df_normalizado_hospedagem.info()

df_normalizado_hospedagem['preco'].apply(lambda x: x.replace('$', '').replace(',',''))

df_normalizado_hospedagem['preco'] = df_normalizado_hospedagem['preco'].apply(lambda x: x.replace('$', '').replace(',',''))

df_normalizado_hospedagem['taxa_deposito'] = df_normalizado_hospedagem['taxa_deposito'].apply(lambda x: x.replace('$', '').replace(',',''))
df_normalizado_hospedagem['taxa_limpeza'] = df_normalizado_hospedagem['taxa_limpeza'].apply(lambda x: x.replace('$', '').replace(',',''))

df_normalizado_hospedagem.head()

col_float = ['taxa_deposito', 'taxa_limpeza', 'preco']

df_normalizado_hospedagem[col_float].astype(np.float64)

df_normalizado_hospedagem[col_float] = df_normalizado_hospedagem[col_float].astype(np.float64)

df_normalizado_hospedagem.info()

df_normalizado_hospedagem['descricao_local'].str.lower()

df_normalizado_hospedagem['descricao_local'] = df_normalizado_hospedagem['descricao_local'].str.lower()

df_normalizado_hospedagem.head()

df_normalizado_hospedagem['descricao_local'].str.replace('[^a-zA-Z0-9\-\']', ' ', regex=True)

df_normalizado_hospedagem['descricao_local'] = df_normalizado_hospedagem['descricao_local'].str.replace('[^a-zA-Z0-9\-\']', ' ', regex=True)

df_normalizado_hospedagem['descricao_local'].str.replace('(?<!\w)-(?!\w)', ' ', regex=True)

df_normalizado_hospedagem['descricao_local'] = df_normalizado_hospedagem['descricao_local'].str.replace('(?<!\w)-(?!\w)', ' ', regex=True)

df_normalizado_hospedagem['descricao_local'].str.split()

df_normalizado_hospedagem['descricao_local'] = df_normalizado_hospedagem['descricao_local'].str.split()

df_normalizado_hospedagem.head()

df_normalizado_hospedagem['comodidades'].str.replace('\{|}|\"', '', regex=True)

df_normalizado_hospedagem['comodidades'] = df_normalizado_hospedagem['comodidades'].str.replace('\{|}|\"', '', regex=True)

df_normalizado_hospedagem.head()

df_normalizado_hospedagem['comodidades'].str.split(',')

df_normalizado_hospedagem['comodidades'] = df_normalizado_hospedagem['comodidades'].str.split(',')

df_normalizado_hospedagem.head()

df_normalizado_hospedagem['descricao_vizinhanca'].str.lower()

df_normalizado_hospedagem['descricao_vizinhanca'] = df_normalizado_hospedagem['descricao_vizinhanca'].str.lower()

df_normalizado_hospedagem['descricao_vizinhanca'].str.replace('[^a-zA-Z0-9\-\']', ' ', regex=True)

df_normalizado_hospedagem['descricao_vizinhanca'] = df_normalizado_hospedagem['descricao_vizinhanca'].str.replace('[^a-zA-Z0-9\-\']', ' ', regex=True)

df_normalizado_hospedagem['descricao_vizinhanca'].str.replace('(?<!\w)-(?!\w)', ' ', regex=True)

df_normalizado_hospedagem['descricao_vizinhanca'] = df_normalizado_hospedagem['descricao_vizinhanca'].str.replace('(?<!\w)-(?!\w)', ' ', regex=True)

df_normalizado_hospedagem['descricao_vizinhanca'].str.split()

df_normalizado_hospedagem['descricao_vizinhanca'] = df_normalizado_hospedagem['descricao_vizinhanca'].str.split()

df_normalizado_hospedagem.head()

pd.read_json(imoveis_disponiveis).head()

df_data = pd.read_json(imoveis_disponiveis)

df_data['data'].info()

pd.to_datetime(df_data['data'])

df_data['data'] = pd.to_datetime(df_data['data'])

df_data.head()

df_data['data'].dt.strftime('%Y-%m')

df_data.groupby(df_data['data'].dt.strftime('%Y-%m'))['vaga_disponivel'].sum()

subset = df_data.groupby(df_data['data'].dt.strftime('%Y-%m'))['vaga_disponivel'].sum()

subset.head()

df_data['preco']

df_data.fillna('0.0')

df_data['preco'] = df_data['preco'].fillna('0.0')

df_data['preco'].apply(lambda x: x.replace('$', '').replace(',', ''))

df_data['preco'] = df_data['preco'].apply(lambda x: x.replace('$', '').replace(',', ''))

df_data['preco'].astype(np.float64)

df_data['preco'] = df_data['preco'].astype(np.float64)

df_data.head()

